### Listar todos os Usuario
GET http://localhost:3000/
Accept: application/json



### cadastrar um Usuario
POST http://localhost:3000/
Content-Type: application/json

{
 "nome": " Bryan Lucas",
 "email" : "bryan@teste.com",
 "senha_hash":22222222,
  "tipo": "aluno"
}

###

### Buscar Usuario por ID
GET http://localhost:3000/1
Accept: application/json

###

### Atualizar Usuario
PUT http://localhost:3000/2
Content-Type: application/json

{
 "nome": " Bryan Oliveira",
 "email" : "bryan@teste.com",
 "senha_hash":22222222,
  "tipo": "aluno"
}

###

### Deletar Usuario
DELETE http://localhost:3000/1

# teste empresas

### criar 

POST http://localhost:3000/desafios
Content-Type: application/json

{
 "titulo": "Bryan Lucas",
 "descricao": "Testando, testando, teste",
 "area": "Tecnologia",
 "prazo": "2023-12-31",
 "recursos": "Computador, internet",
 "condicao": "Completo"
}

