### Listar todos os Usuario
GET http://localhost:3000/conectaEPT
Accept: application/json



### Criar um Usuario
POST http://localhost:3000/users/
Content-Type: application/json

{
 "nome": "bryan Lucas",
 "email" : "bryan@teste.com",
 "senha_hash":22222222,
  "tipo": "aluno"
}

###

### Buscar Usuario por ID
GET http://localhost:3000/usuario/
Accept: application/json

###

### Atualizar Usuario
PUT http://localhost:3000/usuario/15
Content-Type: application/json

{
  
   "titulo": "O Pequeno Príncipe",
   "autor": "Antoine de Saint-Exupéry",
  "disponivel": "0"
}

###

### Deletar Usuario
DELETE http://localhost:3000/usuario/14
